name: Linters

on: pull_request

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
      - name: Run ESLint
        run: npx eslint "**/*.{js,jsx}"
  nodechecker:
    name: node_modules Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check node_modules Existence
        run: |
          if [ -d "node_modules/" ]; then
            echo "Error: The node_modules/ folder was pushed to the repo."
            echo "Please remove it from the GitHub repository and try again."
            exit 1
          fi
